if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VARIABLE)
    message(FATAL_ERROR "INPUT, OUTPUT, and VARIABLE are required")
endif()

file(READ "${INPUT}" binary_hex HEX)
string(LENGTH "${binary_hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")

set(contents "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n")
string(APPEND contents "namespace xeo3::vgpu::generated {\n")
string(APPEND contents "inline constexpr std::uint8_t ${VARIABLE}[] = {\n")

set(offset 0)
while(offset LESS hex_length)
    math(EXPR remaining "${hex_length} - ${offset}")
    if(remaining GREATER 32)
        set(line_length 32)
    else()
        set(line_length ${remaining})
    endif()
    string(SUBSTRING "${binary_hex}" ${offset} ${line_length} line_hex)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " line_bytes "${line_hex}")
    string(APPEND contents "    ${line_bytes}\n")
    math(EXPR offset "${offset} + ${line_length}")
endwhile()

string(APPEND contents "};\n")
string(APPEND contents "inline constexpr std::size_t ${VARIABLE}Size = ${byte_count};\n")
string(APPEND contents "} // namespace xeo3::vgpu::generated\n")
file(WRITE "${OUTPUT}" "${contents}")
